/* Welcome to the SQL mini project. For this project, you will use
Springboard' online SQL platform, which you can log into through the
following link:

https://sql.springboard.com/
Username: student
Password: learn_sql@springboard

The data you need is in the "country_club" database. This database
contains 3 tables:
    i) the "Bookings" table,
    ii) the "Facilities" table, and
    iii) the "Members" table.

Note that, if you need to, you can also download these tables locally.

In the mini project, you'll be asked a series of questions. You can
solve them using the platform, but for the final deliverable,
paste the code for each solution into this script, and upload it
to your GitHub.

Before starting with the questions, feel free to take your time,
exploring the data, and getting acquainted with the 3 tables. */



/* Q1: Some of the facilities charge a fee to members, but some do not.
Please list the names of the facilities that do. */

Squash Court, Tennis Court 1, Tennis Court 2, Massage Room 1, Massage Room 2

Host: localhost
Database: country_club
Generation Time: Jan 23, 2020 at 10:09 AM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: SELECT * FROM `Facilities` WHERE membercost > 0 ORDER BY `Facilities`.`guestcost` ASC LIMIT 0, 30 ;
Rows: 5

facid	name	membercost	guestcost	initialoutlay	monthlymaintenance	
6	Squash Court	3.5	17.5	5000	80
0	Tennis Court 1	5.0	25.0	10000	200
1	Tennis Court 2	5.0	25.0	8000	200
4	Massage Room 1	9.9	80.0	4000	3000
5	Massage Room 2	9.9	80.0	4000	3000


/* Q2: How many facilities do not charge a fee to members? */

4

Host: localhost
Database: country_club
Generation Time: Jan 23, 2020 at 10:24 AM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: SELECT * FROM `Facilities` Where membercost = 0 ORDER BY `Facilities`.`name` ASC LIMIT 0, 30 ;
Rows: 4

facid	name	membercost	guestcost	initialoutlay	monthlymaintenance	
2	Badminton Court	0.0	15.5	4000	50
8	Pool Table	0.0	5.0	400	15
7	Snooker Table	0.0	5.0	450	15
3	Table Tennis	0.0	5.0	320	10


/* Q3: How can you produce a list of facilities that charge a fee to members,
where the fee is less than 20% of the facility's monthly maintenance cost?
Return the facid, facility name, member cost, and monthly maintenance of the
facilities in question. */

Host: localhost
Database: country_club
Generation Time: Jan 23, 2020 at 10:45 AM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: SELECT * FROM `Facilities` WHERE `membercost`* .2 < `monthlymaintenance` ORDER BY `Facilities`.`name` ASC LIMIT 0, 30 ;
Rows: 9

name	membercost	guestcost	initialoutlay	monthlymaintenance	facid	
Badminton Court	0.0	15.5	4000	50	2
Massage Room 1	9.9	80.0	4000	3000	4
Massage Room 2	9.9	80.0	4000	3000	5
Pool Table	0.0	5.0	400	15	8
Snooker Table	0.0	5.0	450	15	7
Squash Court	3.5	17.5	5000	80	6
Table Tennis	0.0	5.0	320	10	3
Tennis Court 1	5.0	25.0	10000	200	0
Tennis Court 2	5.0	25.0	8000	200	1

/* Q4: How can you retrieve the details of facilities with ID 1 and 5?
Write the query without using the OR operator. */

Host: localhost
Database: country_club
Generation Time: Jan 23, 2020 at 11:01 AM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: SELECT * FROM `Facilities` WHERE `facid` IN (1,5) ORDER BY `Facilities`.`name` ASC LIMIT 0, 30 ;
Rows: 2

name	membercost	guestcost	initialoutlay	monthlymaintenance	facid	
Massage Room 2	9.9	80.0	4000	3000	5
Tennis Court 2	5.0	25.0	8000	200	1


/* Q5: How can you produce a list of facilities, with each labelled as
'cheap' or 'expensive', depending on if their monthly maintenance cost is
more than $100? Return the name and monthly maintenance of the facilities
in question. */

Host: localhost
Database: country_club
Generation Time: Jan 23, 2020 at 01:05 PM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: SELECT * FROM `Facilities` WHERE `monthlymaintenance` > 100 ORDER BY `Facilities`.`facid` DESC LIMIT 0, 30 ;
Rows: 4

name	membercost	guestcost	initialoutlay	monthlymaintenance	facid	
Massage Room 2	9.9	80.0	4000	3000	5
Massage Room 1	9.9	80.0	4000	3000	4
Tennis Court 2	5.0	25.0	8000	200	1
Tennis Court 1	5.0	25.0	10000	200	0

/* Q6: You'd like to get the first and last name of the last member(s)
who signed up. Do not use the LIMIT clause for your solution. */
ost: localhost
Database: country_club
Generation Time: Jan 23, 2020 at 12:01 PM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: SELECT `firstname`, `surname` , `joindate` FROM `Members` LIMIT 0, 30 ;
Rows: 30

 This table does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.
firstname	surname	joindate	
GUEST	GUEST	2012-07-01 00:00:00
Darren	Smith	2012-07-02 12:02:05
Tracy	Smith	2012-07-02 12:08:23
Tim	Rownam	2012-07-03 09:32:15
Janice	Joplette	2012-07-03 10:25:05
Gerald	Butters	2012-07-09 10:44:09
Burton	Tracy	2012-07-15 08:52:55
Nancy	Dare	2012-07-25 08:59:12
Tim	Boothe	2012-07-25 16:02:35
Ponder	Stibbons	2012-07-25 17:09:05
Charles	Owen	2012-08-03 19:42:37
David	Jones	2012-08-06 16:32:55
Anne	Baker	2012-08-10 14:23:22
Jemima	Farrell	2012-08-10 14:28:01
Jack	Smith	2012-08-10 16:22:05
Florence	Bader	2012-08-10 17:52:03
Timothy	Baker	2012-08-15 10:34:25
David	Pinker	2012-08-16 11:32:47
Matthew	Genting	2012-08-19 14:55:55
Anna	Mackenzie	2012-08-26 09:32:05
Joan	Coplin	2012-08-29 08:32:41
Ramnaresh	Sarwin	2012-09-01 08:44:42
Douglas	Jones	2012-09-02 18:43:05
Henrietta	Rumney	2012-09-05 08:42:35
David	Farrell	2012-09-15 08:22:05
Henry	Worthington-Smyth	2012-09-17 12:27:15
Millicent	Purview	2012-09-18 19:04:01
Hyacinth	Tupperware	2012-09-18 19:32:05
John	Hunt	2012-09-19 11:32:45
Erica	Crumpet	2012-09-22 08:36:38

/* Q7: How can you produce a list of all members who have used a tennis court?
Include in your output the name of the court, and the name of the member
formatted as a single column. Ensure no duplicate data, and order by
the member name. */


Generation Time: Jan 24, 2020 at 11:51 AM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: Select name, firstname||surname AS "Customer Name" FROM Facilities, Members WHERE name = 'tennis court 1' OR name = 'tennis court 2' LIMIT 0, 30 ;
Rows: 30

 This table does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.
name	        Customer Name	
Tennis Court 1	GUEST	GUEST
Tennis Court 2	GUEST	GUEST
Tennis Court 1	Darren	Smith
Tennis Court 2	Darren	Smith
Tennis Court 1	Tracy	Smith
Tennis Court 2	Tracy	Smith
Tennis Court 1	Tim	Rownam
Tennis Court 2	Tim	Rownam
Tennis Court 1	Janice	Joplette
Tennis Court 2	Janice	Joplette
Tennis Court 1	Gerald	Butters
Tennis Court 2	Gerald	Butters
Tennis Court 1	Burton	Tracy
Tennis Court 2	Burton	Tracy
Tennis Court 1	Nancy	Dare
Tennis Court 2	Nancy	Dare
Tennis Court 1	Tim	Boothe
Tennis Court 2	Tim	Boothe
Tennis Court 1	Ponder	Stibbons
Tennis Court 2	Ponder	Stibbons
Tennis Court 1	Charles	Owen
Tennis Court 2	Charles	Owen
Tennis Court 1	David	Jones
Tennis Court 2	David	Jones
Tennis Court 1	Anne	Baker
Tennis Court 2	Anne	Baker
Tennis Court 1	Jemima	Farrell
Tennis Court 2	Jemima	Farrell
Tennis Court 1	Jack	Smith
Tennis Court 2	Jack	Smith

/* Q8: How can you produce a list of bookings on the day of 2012-09-14 which
will cost the member (or guest) more than $30? Remember that guests have
different costs to members (the listed costs are per half-hour 'slot'), and
the guest user's ID is always 0. Include in your output the name of the
facility, the name of the member formatted as a single column, and the cost.
Order by descending cost, and do not use any subqueries. */

Host: localhost
Database: country_club
Generation Time: Jan 25, 2020 at 09:24 AM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: SELECT membercost, guestcost, firstname, surname, name, starttime FROM Facilities, Members, Bookings WHERE starttime = 2012-09-14 AND membercost > 29 OR guestcost > 29 LIMIT 0, 30 ;
Rows: 30

 This table does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.
membercost	guestcost	firstname	surname	name	starttime	
9.9	80.0	GUEST	GUEST	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	GUEST	GUEST	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Darren	Smith	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Darren	Smith	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Tracy	Smith	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Tracy	Smith	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Tim	Rownam	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Tim	Rownam	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Janice	Joplette	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Janice	Joplette	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Gerald	Butters	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Gerald	Butters	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Burton	Tracy	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Burton	Tracy	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Nancy	Dare	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Nancy	Dare	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Tim	Boothe	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Tim	Boothe	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Ponder	Stibbons	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Ponder	Stibbons	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Charles	Owen	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Charles	Owen	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	David	Jones	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	David	Jones	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Anne	Baker	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Anne	Baker	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Jemima	Farrell	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Jemima	Farrell	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Jack	Smith	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Jack	Smith	Massage Room 2	2012-07-03 11:00:00




/* Q9: This time, produce the same result as in Q8, but using a subquery. */

Generation Time: Jan 25, 2020 at 09:57 AM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: SELECT membercost, guestcost, firstname, surname, name, starttime FROM Facilities, Members, Bookings WHERE membercost > 29 OR guestcost > 29 AND starttime IN (2012) LIMIT 0, 30 ;
Rows: 30

 This table does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.
membercost	guestcost	firstname	surname	name	starttime	
9.9	80.0	GUEST	GUEST	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	GUEST	GUEST	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Darren	Smith	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Darren	Smith	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Tracy	Smith	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Tracy	Smith	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Tim	Rownam	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Tim	Rownam	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Janice	Joplette	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Janice	Joplette	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Gerald	Butters	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Gerald	Butters	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Burton	Tracy	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Burton	Tracy	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Nancy	Dare	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Nancy	Dare	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Tim	Boothe	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Tim	Boothe	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Ponder	Stibbons	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Ponder	Stibbons	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Charles	Owen	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Charles	Owen	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	David	Jones	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	David	Jones	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Anne	Baker	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Anne	Baker	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Jemima	Farrell	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Jemima	Farrell	Massage Room 2	2012-07-03 11:00:00
9.9	80.0	Jack	Smith	Massage Room 1	2012-07-03 11:00:00
9.9	80.0	Jack	Smith	Massage Room 2	2012-07-03 11:00:00


/* Q10: Produce a list of facilities with a total revenue less than 1000.
The output of facility name and total revenue, sorted by revenue. Remember
that there's a different cost for guests and members! */

Database: country_club
Generation Time: Jan 25, 2020 at 10:01 AM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: SELECT name, membercost + guestcost "Total Revenue" FROM Facilities ORDER by "Total Revenue" LIMIT 0, 30 ;
Rows: 9

 This table does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.
name	Total Revenue	
Tennis Court 1	30.0
Tennis Court 2	30.0
Badminton Court	15.5
Table Tennis	5.0
Massage Room 1	89.9
Massage Room 2	89.9
Squash Court	21.0
Snooker Table	5.0
Pool Table	5.0
